FROM quay.io/centos/centos:stream9
RUN yum update -y && yum install -y rpm-build make rpmdevtools tree rpmlint vim && yum clean all && groupadd -g 1000 -o builder && useradd -m -u 1000 -g 1000 -o -s /usr/bin/bash builder
USER builder
WORKDIR /home/builder
RUN rpmdev-setuptree && mkdir ~/data
CMD ["/home/builder/data/entrypoint-rpm.sh"]
